#!/usr/bin/env python3
"""Generate pasteable Vertex AI Studio turns for the quiz funnel.

Reads the catalog out of pulumi/agent/prompt.md so every question and answer
string is byte-identical to what the agent is instructed to emit, and wraps
each turn in the exact envelope apps/backend/src/app.service.ts sends.

    python3 scripts/playground_turns.py > playground-test-turns.md
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROMPT = ROOT / 'pulumi/agent/prompt.md'
CATALOG = ROOT / 'apps/backend/catalog/sunglasses.jsonl'

# Mirrors app.service.ts: override() + MAX_QUESTIONS + PROMPT_FIELDS.
MAX_QUESTIONS = 8
QUESTION_SHAPE = ('{"nextQuestion": {"question": string, "answers": string[], '
                  '"typeOfQuestion": "singleChoice" | "multiChoice"}}')
RECOMMEND_SHAPE = '{"heroId": string, "alternativeIds": [string, string], "why": [string, string, string]}'
PROMPT_FIELDS = ['id', 'title', 'price', 'face_shapes', 'frame_material', 'lens_type',
                 'aesthetic_archetype', 'best_for_activities', 'solves_pain_points',
                 'pitch_bullet_points']

def override(shape, *rest):
    return '\n'.join(['TASK OVERRIDE. For this request only, ignore any output format described in your system instructions.',
                      'Return exactly this JSON object and nothing else:', shape, *rest])

def load_catalog():
    """Every question the prompt embeds, keyed by id (Q4.2b keyed by family)."""
    block = re.search(r'### 4\. THE QUESTION CATALOG.*?\n```\n(.*?)\n```', PROMPT.read_text(), re.S).group(1)
    out = {}
    for line in block.splitlines():
        q = json.loads(line)
        out[q['id'] + ('/' + q['whenQ42aValue'] if 'whenQ42aValue' in q else '')] = q
    return out

def turn(q, picks):
    """One history row: the question as asked, plus what the user clicked."""
    for p in picks:
        assert p in q['answers'], f"{p!r} is not an option of {q['id']}"
    return {'question': q['question'], 'answers': q['answers'],
            'typeOfQuestion': q['typeOfQuestion'], 'selectedAnswers': picks}

C = load_catalog()

PERSONAS = {
    'A. Classic driver, frames slip, high glare': [
        ('Q1.1a',  ['About equal']),
        ('Q1.2',   ['Too tight, they pinch my temples']),
        ('Q2.1',   ['They slide down my nose constantly']),
        ('Q3.1',   ['Driving and road trips', 'Water, beach, boating, snow']),
        ('Q4.1',   ['Classic dark, standard sun protection']),
        ('Q4.2a',  ['Timeless and classic (heritage shapes, aviators, wayfarers)']),
        ('Q4.2b/axis_family_classic', ['Classic Aviation (Gold teardrop aviator with double brow bar)']),
        ('Q2.5',   ['Must be featherlight \u2014 I dislike feeling frames']),
    ],
    'B. Bold city wearer, pinch marks, wants presence': [
        ('Q1.1a',  ['Noticeably longer than wide']),
        ('Q1.2',   ['About right']),
        ('Q2.1',   ['They leave red pinch marks on my nose']),
        ('Q3.1',   ['City and everyday, commuting, terraces']),
        ('Q4.1',   ['Fully dark, nobody sees my eyes']),
        ('Q4.2a',  ['Bold and architectural (heavy volume, sharp geometry, high-tech)']),
        ('Q4.2b/axis_family_bold', ['Architectural & Bold Brutalism (Heavy slab acetate, sharp geometric flat-top)']),
        ('Q4.5',   ['Classic Black or Dark Matte (sleek & versatile)']),
    ],
}

def next_question_message(history):
    return override(QUESTION_SHAPE,
                    'Return {"nextQuestion": null} if you have enough information.', '',
                    'Your task: pick the single most useful next question for this user. Never repeat a question already asked.',
                    'Questions asked so far and the answers the user selected, as JSON:',
                    json.dumps(history))

def recommend_message(history):
    items = [json.loads(l) for l in CATALOG.read_text().splitlines() if l.strip()]
    slim = json.dumps([{k: i.get(k) for k in PROMPT_FIELDS} for i in items])
    return override(RECOMMEND_SHAPE,
                    '"why" are short, persuasive reasons for the hero pick, each tied to a specific answer the user gave.', '',
                    'Your task: pick the best sunglasses for this user. Use only ids from the catalog below.',
                    'Questions asked and the answers the user selected, as JSON:',
                    json.dumps(history), '',
                    'Sunglasses catalog, as JSON:', slim)

print(f"""# Playground test turns

Generated by `scripts/playground_turns.py`. Regenerate after changing `pulumi/agent/prompt.md`.

**Setup in Vertex AI Studio:** system instruction is the full text of [`pulumi/agent/prompt.md`](pulumi/agent/prompt.md). Model `gemini-2.5-flash`, `responseMimeType: application/json`, `thinkingBudget: 0` (matches `pulumi/index.ts`).

The agent is stateless (`user_id: 'quizly'`, no session id), so **every turn below is a standalone single-turn prompt**. Paste one, read the reply, discard the chat, paste the next. Do not build up a conversation.

Each turn shows the exact message `apps/backend/src/app.service.ts` would send, and what a correct reply looks like.
""")

for name, script in PERSONAS.items():
    print(f"\n---\n\n## Persona {name}\n")
    history = []
    for i, (qid, picks) in enumerate(script):
        q = C[qid]
        print(f"### Turn {i + 1} (N={i}), expect `{qid.split('/')[0]}`\n")
        print("```text")
        print(next_question_message(history))
        print("```\n")
        print(f"Correct reply:\n")
        print("```json")
        print(json.dumps({'nextQuestion': {k: q[k] for k in ('question', 'answers', 'typeOfQuestion')}}))
        print("```\n")
        history.append(turn(q, picks))
    print(f"### Turn {MAX_QUESTIONS + 1} (N={MAX_QUESTIONS}): backend short-circuits\n")
    print(f"`app.service.ts` returns `{{\"nextQuestion\": null}}` at N >= {MAX_QUESTIONS} without calling the agent, so there is no turn {MAX_QUESTIONS + 1} to test. To check the agent agrees, paste the turn-{MAX_QUESTIONS} message with the full 8-row history and confirm it replies `{{\"nextQuestion\": null}}`.\n")
    print(f"### Recommendation call\n")
    print("```text")
    print(recommend_message(history))
    print("```\n")
    print('Correct reply: one `heroId` and two `alternativeIds` drawn only from the catalog ids above, and three `why` strings each naming something this persona actually answered.\n')
